### ISSUE TITLE
关于README.md

### ISSUE THREAD

**Issue by turstdxj** [Whut-YiRong/ESPT#1]
您好，最近阅读了你们的文章，但是代码部分运行所需要的参数有些不太懂，你们能给出一个简单的demo吗

**Comment by Whut-YiRong** [comment]
你好，我们会于7月23日更新我们的readme，提供训练使用的命令，主要的参数都在experiment文件夹的train.sh中，请问具体有哪些参数不太懂呢？

**Comment by Whut-YiRong** [comment]
> 您好，最近阅读了你们的文章，但是代码部分运行所需要的参数有些不太懂，你们能给出一个简单的demo吗

我们已经更新了我们的Readme，您可以根据相应流程，训练得到自己的模型并测试，如果您有任何其他问题，也可以发邮件联系我们，我们的邮箱地址是：yrong@whut.edu.cn

**Comment by turstdxj** [comment]
谢谢您的回答，我已经看到你们更新的readme了
